### ISSUE TITLE
export to csv function - add new rows for NE?

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-middle-layer#113]
currently, we can export the following elements:
uid	type	language	title	content	size	country	newspaper	issue	pages	nb_pages	relevance	year	is_on_front	date	[total:2344,available:2400]		

would it be possible to add the Named entities (mentions), one column for the persons (organisations?) another for places?

**Comment by danieleguido** [comment]
Thanks! I put the "bug" label because of the article contents:
- [ ] add mentions of people and location
- [ ] fix delimiters for contents
