### ISSUE TITLE
searchFacets service : add order_by

### ISSUE THREAD

**Issue by PaulSchroeder** [impresso/impresso-middle-layer#153]

**Comment by danieleguido** [comment]
Hi @PaulSchroeder, there are limits to what we can ask Solr for a specific facet as we perform faceting on fields containing string uid identifier... :(
For example to get the number of results per newspaper, we use the field the `meta_journal_s` as facet: this field contains only the UID of the newspaper, that is, `JDG` for journal de Geneve.
Ordering or searching the facet doesn't make any sense on the uid field and it is not possible given the current structure.
I then suggest to use the `/search-facets` endpoint only for pagination; once a search is performed, we must use the service relative to the search type.
