### ISSUE TITLE
/search: add highlights for results in `content_txt_de` solr field

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-middle-layer#156]
example query to implement the highlighter with multiple field support:
`/select?q=meta_journal_s:NZZ%20AND%20content_txt_de:einstein&fl=id&hl=on&rows=1&hl.fl=content_txt_de,content_txt_fr&hl.snippets=10&hl.fragsize=100`

@e-maud apparently the current highlight plugin only get the result for the field `content_txt_fr`? Check the differences between `/select?q=meta_journal_s:GDL%20AND%20content_txt_fr:einstein&hl=on&rows=1` and
`/select?q=meta_journal_s:NZZ%20AND%20content_txt_de:einstein&hl=on&rows=1`

**Comment by theorm** [comment]
I can see highlights for German. Assuming this is not an issue anymore.
