### ISSUE TITLE
/search endpoint: IIIF for issues on CC not working

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-middle-layer#168]
Connected to #71 
http://localhost:8081/#/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221737-01-01T00%3A00%3A00Z%20TO%201804-04-28T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by theorm** [comment]
Looks like it's fixed
