### ISSUE TITLE
Articles with no topics should not be related to other articles

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-middle-layer#223]
even if these are also articles with no topic ;)
example: https://impresso-project.ch/app/issue/LSE-1960-11-11-a/page/LSE-1960-11-11-a-p0009/article/LSE-1960-11-11-a-i0073

**Comment by theorm** [comment]
I can see that this article has a single topic and all "similar articles" have the same topic. Am I missing something or it has been fixed?

<img width="729" alt="Screen Shot 2020-05-04 at 11 25 35" src="https://user-images.githubusercontent.com/89853/80952475-0301a000-8dfa-11ea-8d42-53b528cba057.png">

**Comment by theorm** [comment]
Hi @Bunoute , would you be able to check if the problem is still there? 

Thank you.

**Comment by Bunoute** [comment]
indeed, they now have all the same (weird) topic :) so i guess, it's working as it should.
