### ISSUE TITLE
collection.countItems is not updated ...

### ISSUE THREAD

**Issue by PaulSchroeder** [impresso/impresso-middle-layer#273]
... when adding or removing items to a collection.

**Comment by theorm** [comment]
Hi @PaulSchroeder , can you please add a link to the page where and a brief description of what this field is for, why it needs to be updated and when? This part is completely new to me. Thank you.

**Comment by PaulSchroeder** [comment]
Hi @theorm on [collection page](http://localhost:8080/collections/), in the collection list, the number of items (articles) in the collection are displayed. collections have required property `countItems` to return this number. 

For new manual collections, nothing is returned. For bulk collections (save / export > create collection from search results ) I always get the max. number (for me) of 10,000 results, but that's another bug

**Comment by danieleguido** [comment]
(fixed on impresso-user-admin)
