### ISSUE TITLE
bug: no return data for some newspaper issues

### ISSUE THREAD

**Issue by tvanbeek** [impresso/impresso-middle-layer#43]
When I do this request to the middle layer  `47:4282["get","pages","JDG-1997-12-30-a-p0002",{}]` it returns the following error

```
className: "not-found"
code: 404
data: undefined
errors: {}
message: "Error"
name: "NotFound"
type: "FeathersError"
```

It seems as if the middle layer has no page data if there are no articles for that page. As you can see in the table of contents screenshot, we have articles on pages 5, 19, 24, 25 and 32 but no articles on the other pages. As a result we can not load the page data for any of the other pages. But the thumbnails do work.

![screenshot 2018-11-15 at 13 53 55](https://user-images.githubusercontent.com/3518980/48554449-bd3bd980-e8de-11e8-89b4-c0776530e927.png)

Check out the live example [here](https://impresso-project.ch/dev/#/issue/JDG-1997-12-30-a/page/JDG-1997-12-30-a-p0005/article/JDG-1997-12-30-a-i0009)

**Comment by danieleguido** [comment]
Hi @tvanbeek,
I currently load all the data from SOLR where only articles are stored. This mean that there are pages without any articles, which is not good :)

**Comment by tvanbeek** [comment]
Yes, but the thing is, in the Thumbnail Slider you see previews for all pages in the issue. However, if you try to go to a page that coincidently does not have any articles in the TableOfContents, it doesn't load. So even if you forget about the TableOfContens and just click on page 2 or 3 in the thumbnail slider or pagination on the example page, then the middle layer returns an error. I assume that there is a iiif image because we do get the thumbnail.
