### ISSUE TITLE
Documentation of C2DH enpoints

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-middle-layer#442]
For everyone to know what is where, it would be helpful to please update and add URLs in the "ENDPOINT" tab of the [cheat-sheet](https://docs.google.com/spreadsheets/d/1Z4_w8rnYctjZGk87qKxsEFINVUZFoWvCWtZqKRlC36Y/edit?gid=398475666#gid=398475666).

This spreadsheet is listed on the [GH home readme](https://github.com/impresso/.github-private/blob/main/profile/README.md) an is located in `07-sys-architecture-infra-sustainability`on the drive.

**Comment by theorm** [comment]
Done
