### ISSUE TITLE
Search for multiword strings returns hits for individual words

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-middle-layer#53]
When searching for a person with a multiword name, the interface shows hits for parts of the multiword string.

![image](https://user-images.githubusercontent.com/3041168/49892919-793ee480-fe4a-11e8-8f1e-2a7f759d4c7b.png)

**Comment by danieleguido** [comment]
Should be fixed once we enable the "exact match" by default. THere could be problems with the analyser though:

https://stackoverflow.com/questions/9426678/lower-case-and-upper-case-in-solr-keyword?answertab=active#tab-top

**Comment by simon-clematide** [comment]
Just a comment: if I am understanding correctly (not really a SOLR whisperer myself) the highlighting of phrase search terms will always include  occurrences of parts of the phrase somewhere in the article by default.
