### ISSUE TITLE
collections/collectible-items > add order_by to query

### ISSUE THREAD

**Issue by PaulSchroeder** [impresso/impresso-middle-layer#93]
what will be the options, e.g.
date
date-
dateAdded
dateAdded-

?

**Comment by danieleguido** [comment]
options will be: 
    
    ['-dateAdded', 'dateAdded', '-itemDate', 'itemDate']

the params is `order_by` and it will take one of these 4 choices, e.g. `order_by: 'dateAdded'`.

If no param is sent, default is `-dateAdded`

It will be in the coming release, but you can prepare the mechanism already.
